import os
import json
import argparse
import pandas as pd
import numpy as np
import requests # For Ollama
from tqdm import tqdm
import datetime
from collections import defaultdict
import string
from ast import literal_eval

# Assuming defend.py is in the same directory or accessible via PYTHONPATH
from defend import Defend # dEFEND model class

# --- Configuration ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__)) # Should be dEFEND-v2/raw/

# 1. Path to the folder containing your trained dEFEND models and tokenizers
#    Expected structure: ./saved-models/<dataset_name>_defend_model.h5
DEFEND_MODEL_DIR = os.path.join(BASE_DIR, "saved-models")

# 2. Path to the folder containing BERT SHAP token analysis results (same as RoBERTa attack)
#    Expected structure: <BERT_SHAP_OUTPUT_DIR>/<dataset>/token_confidence/<BERT_MODEL_NAME>/all_tokens/
BERT_TOKENIZER_FOLDER = "/home/shoaib/attack-on-fake-news/bert-fake-news/logs/results" # From RoBERTa script
BERT_TOKEN_DIR_BASE = os.path.join(BERT_TOKENIZER_FOLDER)
BERT_MODEL_FILENAME_FOR_TOKENS = "bert-fake-news-model.pt_prioritized_comment_first_style-best.pt" # From RoBERTa script

# 3. Path to pre-generated comments (from TextCNN/BERT attack runs)
PRE_GENERATED_COMMENTS_BASE_DIR = "/home/shoaib/attack-on-fake-news/TextCNN-v2/logs/saved-models/explanations" # From RoBERTa script

# 4. Path to the directory containing dEFEND's predictions CSV file.
#    The CSV file itself should be named 'predictions.csv'.
#    Generated by generate_defend_predictions.py
#    Expected structure: ./prediction_results_defend/<dataset_name>/predictions.csv
DEFEND_PREDICTIONS_DIR_BASE = os.path.join(BASE_DIR, "prediction_results_defend")

# 5. Path to the original datasets
DATASET_FOLDER = "/home/shoaib/attack-on-fake-news/fake_news_data" # Standard location

# 6. Output directory for dEFEND attack results
ATTACK_OUTPUT_FOLDER = os.path.join(BASE_DIR, "attack_results_defend_vs_bert_tokens")

# --- Attacker Class ---

class DefendAttackerWithBertTokens:
    def __init__(self, dataset_name):
        self.dataset_name = dataset_name

        # --- Load dEFEND Model ---
        self.defend_model_path_dir = DEFEND_MODEL_DIR
        self.defend_model_filename = f"{self.dataset_name}_defend_model.h5"
        
        if not os.path.exists(os.path.join(self.defend_model_path_dir, self.defend_model_filename)):
            raise FileNotFoundError(
                f"dEFEND model file not found at "
                f"{os.path.join(self.defend_model_path_dir, self.defend_model_filename)}"
            )
        
        # Defend class loads its own tokenizer internally based on the dataset
        self.defend_model = Defend(self.dataset_name) # This initializes tokenizer etc.
        try:
            self.defend_model.load_weights(
                saved_model_dir=self.defend_model_path_dir,
                saved_model_filename=self.defend_model_filename
            )
            print(f"dEFEND model loaded for dataset: {self.dataset_name} from {self.defend_model_path_dir}")
        except Exception as e:
            print(f"Error loading dEFEND model weights: {e}")
            raise

        # --- Setup Paths ---
        self.results_dir = os.path.join(DEFEND_PREDICTIONS_DIR_BASE, self.dataset_name) # dEFEND's predictions

        self.bert_token_dir = os.path.join(
            BERT_TOKEN_DIR_BASE,
            self.dataset_name, "token_confidence", BERT_MODEL_FILENAME_FOR_TOKENS, "all_tokens"
        )
        if not os.path.exists(self.bert_token_dir):
             print(f"WARNING: BERT token directory not found at {self.bert_token_dir}. Token loading will fail.")

        self.attack_dir = os.path.join(ATTACK_OUTPUT_FOLDER, self.dataset_name)
        os.makedirs(self.attack_dir, exist_ok=True)

    def load_bert_tokens(self, article_id, is_fake_target, top_n=200):
        """
        Load tokens for a specific article ID based on its classification (fake or real)
        from the BERT SHAP all_tokens directory. (Copied from RobertaAttackerWithBertTokens)
        """
        tokens_path = os.path.join(self.bert_token_dir, f"{article_id}.csv")
        if os.path.exists(tokens_path):
            tokens_df = pd.read_csv(tokens_path)
            duplicate_tokens = tokens_df.groupby("Token")["Direction"].nunique()
            conflicting_tokens = duplicate_tokens[duplicate_tokens > 1].index.tolist()
            target_direction = "REAL" if is_fake_target else "FAKE"
            tokens_df = tokens_df[(tokens_df["Direction"] == target_direction) & (~tokens_df["Token"].isin(conflicting_tokens))]
            tokens_df = tokens_df.sort_values("Confidence", ascending=False)
            tokens = tokens_df.head(top_n)["Token"].tolist()
            tokens = [str(token) for token in tokens if pd.notnull(token) and str(token) not in string.punctuation and len(str(token).strip()) > 0]
            seen = set()
            tokens = [token for token in tokens if not (token in seen or seen.add(token))]
        else:
            print(f"BERT tokens file not found for article ID {article_id}: {tokens_path}")
            tokens = []
        return tokens

    def get_article_content(self, article_id):
        """
        Get original article content and metadata from the test CSV.
        Returns content as a list of sentences and comments as a list of strings.
        """
        test_csv_path = os.path.join(DATASET_FOLDER, f"{self.dataset_name}_test.csv")
        try:
            df = pd.read_csv(test_csv_path, converters={'title': literal_eval, 'content': literal_eval, 'comments': literal_eval})
            article = df[df.iloc[:, 0] == article_id] # Assuming first column is ID

            if article.empty:
                print(f"Article ID {article_id} not found in {test_csv_path}")
                return None, None, None, None

            row = article.iloc[0]
            # dEFEND expects content as list of sentences, comments as list of comment strings
            content_sentences = row['content'] if isinstance(row['content'], list) else [str(row['content'])]
            original_comments_list = row['comments'] if isinstance(row['comments'], list) else [str(row['comments'])]
            
            title_raw = row['title']
            title_str = ' '.join(title_raw) if isinstance(title_raw, list) else str(title_raw)
            actual_label_numeric = int(row['label']) # 0 for REAL, 1 for FAKE

            return content_sentences, original_comments_list, actual_label_numeric, title_str
        except FileNotFoundError:
            print(f"Error: Test dataset file not found at {test_csv_path}")
            return None, None, None, None
        except Exception as e:
            print(f"Error reading or processing article {article_id} from {test_csv_path}: {e}")
            return None, None, None, None

    def process_generated_comment(self, generated_comment):
        """Cleans the raw output from the LLM. (Copied from RobertaAttackerWithBertTokens)"""
        if not generated_comment:
            return None
        # (Identical to RoBERTa version - keeping it concise here for brevity)
        # ... (full cleaning logic from your RoBERTa script) ...
        split_marker = '\n\n\"'
        if split_marker in generated_comment:
            generated_comment = generated_comment.split(split_marker, 1)[-1].strip()
        unwanted_phrases = [
            "Here is a new single line comment that aligns with the REAL classification:",
            "Here is a new single line comment that aligns with the FAKE classification:",
            "Here's a new single-line comment that aligns with the REAL classification:",
            "Here's a new single-line comment that aligns with the FAKE classification:",
            "Here is a single short new comment that aligns with the REAL classification:",
            "Here is a new single line comment that aligns with the overall idea of the title and uses several global tokens for REAL classification:",
            "Here's a new single line comment that aligns with the REAL classification:",
            "Here's the generated comment based on the given input:",
            "Here's a comment that aligns with the FAKE classification:",
            "Here's a comment that aligns with the REAL classification:",
            "Here is a single new comment that aligns with the FAKE classification:",
            "Here is a new comment that aligns with the REAL classification:",
            "Here's a generated comment that aligns with the REAL classification:",
            "Here is a generated comment that aligns with the REAL classification:",
            "Here is a single short new comment that aligns with the REAL classification:",
            "Here's a new short comment that aligns with the REAL classification:",
            "Here is a new single-line comment that aligns with the REAL classification:",
            "Here's a fake comment that aligns with the FAKE classification:"
            "Here's a generated comment that aligns with the FAKE classification:",
            "Here is a single short new comment that aligns with the FAKE classification:",
            "Here is a single new comment that aligns with the REAL classification:",
            "Here is a generated single new comment that aligns with the REAL classification:",
            "Here is a single short new comment that aligns with the FAKE classification:",
            "Here is a new comment that aligns with the FAKE classification:",
            "Here is a new single-line comment that aligns with the overall idea of the post title",
            "Here is a new single line comment that aligns with the overall idea of the title and uses many of the global tokens for REAL classification:"
        ]
        for phrase in unwanted_phrases:
            if phrase in generated_comment:
                generated_comment = generated_comment.replace(phrase, "").strip()
        if generated_comment.startswith("[") and generated_comment.endswith("]"):
            generated_comment = generated_comment[1:-1].strip()
        if generated_comment.startswith("\"") and generated_comment.endswith("\""):
            generated_comment = generated_comment[1:-1].strip()
        return generated_comment.strip()


    def predict_with_defend(self, article_content_sentences_list, article_comments_strings_list):
        """
        Gets prediction from the dEFEND model.
        dEFEND's predict method expects a batch:
        - article_content_sentences_list: e.g., [['sent1', 'sent2']] for a single article batch
        - article_comments_strings_list: e.g., [['comment1', 'comment2']] for a single article batch
        """
        if not article_content_sentences_list or not article_content_sentences_list[0]: # Check if content is empty
            print(f"Warning: Input content is empty for dEFEND prediction.")
            return {'prediction': 'ERROR', 'confidence': 0.0, 'fake_prob': 0.0, 'real_prob': 0.0}
        try:
            # dEFEND model's predict method handles tokenization and padding internally.
            # It expects a list of articles, where each article's content is a list of sentences,
            # and each article's comments is a list of comment strings.
            probabilities_batch = self.defend_model.predict(
                article_content_sentences_list,
                article_comments_strings_list
            )
            
            if probabilities_batch is None or len(probabilities_batch) == 0:
                print("Error: dEFEND prediction returned None or empty.")
                return {'prediction': 'ERROR', 'confidence': 0.0, 'fake_prob': 0.0, 'real_prob': 0.0}

            probas_for_item = probabilities_batch[0] # We are predicting one item at a time here

            # Assuming dEFEND output: [prob_REAL, prob_FAKE] (0 for REAL, 1 for FAKE)
            # Verify this mapping based on dEFEND's training and output.
            # If Defend.predict returns [[prob_REAL, prob_FAKE]], then:
            real_prob = float(probas_for_item[0])
            fake_prob = float(probas_for_item[1])
            
            predicted_idx = np.argmax(probas_for_item)
            pred_label = 'FAKE' if predicted_idx == 1 else 'REAL'
            confidence = float(probas_for_item[predicted_idx])

            return {
                'prediction': pred_label,
                'confidence': confidence,
                'fake_prob': fake_prob,
                'real_prob': real_prob
            }
        except Exception as e:
            # Catching content for logging, be mindful of very long content.
            log_content = str(article_content_sentences_list[0][:2]) if article_content_sentences_list and article_content_sentences_list[0] else "N/A"
            print(f"Error during dEFEND prediction for content '{log_content}...': {e}")
            return {'prediction': 'ERROR', 'confidence': 0.0, 'fake_prob': 0.0, 'real_prob': 0.0}

    def create_comment_generation_prompt(self, title, content_str, comments_str, include_tokens, avoid_tokens, target_class, generated_comments_folder_suffix):
        """Create a prompt to generate a new comment. (Copied from RobertaAttackerWithBertTokens)"""
        # content_str and comments_str are joined strings for the prompt
        if generated_comments_folder_suffix == "title":
            initaize_prompt = f"Given the following post title: {title}"
        elif generated_comments_folder_suffix == "title_article":
            initaize_prompt = f"Given the following post title: {title} and news article: {content_str}"
        elif generated_comments_folder_suffix == "title_cmnts":
            initaize_prompt = f"Given the following post title: {title} and the comments are: {comments_str}"
        else: # title_article_cmnts
            initaize_prompt = f"Given the following post title: {title}, news article: {content_str} and the comments are: {comments_str}"
        
        prompt = f"""
        {initaize_prompt}.
        Write a new single line comment that aligns with the overall idea of the title and alters its classification to "{target_class}".
        The comment is considered as when people share one news article with a comment in a social media.
        WORDS MUST INCLUDE FOR {target_class} CLASSIFICATION:
        {', '.join(include_tokens)}
        WORDS MUST AVOID FOR {target_class} CLASSIFICATION:
        {', '.join(avoid_tokens)}
        INSTRUCTIONS:
        1. Generate a single line very short new comment that aligns with the {target_class} classification.
        2. Include as many of the WORDS for {target_class} classification as possible.
        3. Avoid using the WORDS listed under "WORDS TO AVOID FOR {target_class} CLASSIFICATION".
        4. IMPORTANT: Give ONLY the generated comment as plain text, don't give any introductory and conlusion text.
        """
        return prompt.strip()

    def query_ollama(self, prompt, attack_type, model_name="llama3:8b"):
        """Query Ollama API. (Copied from RobertaAttackerWithBertTokens)"""
        temperature = 0.9 if attack_type == "Real" else 0.7
        url = "http://localhost:11434/api/generate"
        data = {
            "model": model_name, "prompt": prompt, "stream": False,
            "options": {"temperature": temperature, "top_p": 0.9}
        }
        try:
            response = requests.post(url, json=data)
            if response.status_code == 200:
                generated_text = response.json()["response"]
                if "I can't fulfill this request" in generated_text or "violates my policy" in generated_text:
                    print(f"Model {model_name} refused to generate a comment.")
                    return None
                return generated_text.strip()
            else:
                print(f"Error querying Ollama: {response.status_code} - {response.text}")
                return None
        except Exception as e:
            print(f"Exception when querying Ollama: {e}")
            return None

    def verify_token_usage(self, processed_comment, tokens):
        """Verify token usage. (Copied from RobertaAttackerWithBertTokens)"""
        if not processed_comment: return [], 0
        comment_lower = processed_comment.lower()
        used_tokens = [token for token in tokens if token.lower() in comment_lower]
        return used_tokens, len(used_tokens)

    def test_attack_success(self, article_content_sentences, original_comments_for_scenario, comments_to_add_for_attack, is_fake_original_pred_by_defend):
        """
        Compares dEFEND predictions.
        - article_content_sentences: list of sentences for the article.
        - original_comments_for_scenario: list of comment strings for the 'before attack' state.
        - comments_to_add_for_attack: list containing the single generated adversarial comment string.
        - is_fake_original_pred_by_defend: boolean, True if dEFEND initially predicted FAKE for the article.
        """
        # Predict on original state for this scenario (batch of 1)
        original_pred_input_content_batch = [article_content_sentences]
        original_pred_input_comments_batch = [original_comments_for_scenario]
        original_pred = self.predict_with_defend(original_pred_input_content_batch, original_pred_input_comments_batch)

        # Predict on modified state for this scenario (batch of 1)
        modified_comments_list = original_comments_for_scenario + comments_to_add_for_attack
        modified_pred_input_content_batch = [article_content_sentences]
        modified_pred_input_comments_batch = [modified_comments_list]
        modified_pred = self.predict_with_defend(modified_pred_input_content_batch, modified_pred_input_comments_batch)

        target_class = 'REAL' if is_fake_original_pred_by_defend else 'FAKE'
        
        success = (original_pred['prediction'] != 'ERROR' and
                   modified_pred['prediction'] != 'ERROR' and
                   modified_pred['prediction'] == target_class)
        

        # Debugging
        # print(f"--- Debug test_attack_success for article (content: {str(article_content_sentences)[:100]}...) ---")
        # print(f"is_fake_original_pred_by_defend: {is_fake_original_pred_by_defend}")
        # print(f"Target Class: {target_class}")
        # print(f"Original Pred: {original_pred}")
        # print(f"Comments Added: {comments_to_add_for_attack}")
        # print(f"Modified Pred: {modified_pred}")
        # print(f"Success: {success}")
        # print(f"----------------------------------------------------")
        
        return {
            'original_prediction': original_pred,
            'modified_prediction': modified_pred,
            'success': success
        }

    def compare_models(self, predictions_df, generated_comments_folder_suffix, llm_models=None, top_n=200):
        """Attack dEFEND using BERT SHAP tokens and LLMs."""
        if llm_models is None:
            llm_models = ["llama3:8b"]

        comparison_dir = os.path.join(self.attack_dir, f"model_comparison_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}_{generated_comments_folder_suffix}")
        os.makedirs(comparison_dir, exist_ok=True)
        print(f"Comparison directory created: {comparison_dir}")

        comparison_results = defaultdict(list)

        for _, row in tqdm(predictions_df.iterrows(), total=len(predictions_df), desc="Attacking dEFEND"):
            article_id = row['id']
            # This is dEFEND's original prediction on the test set
            predicted_label = row['predicted'] # 'FAKE' or 'REAL'
            is_fake_pred = predicted_label == 'FAKE'
            
            target_class = 'REAL' if is_fake_pred else 'FAKE'
            attack_type = 'Real' if target_class == 'REAL' else 'Fake' # Based on target

            content_sentences, original_comments, _, title_str = self.get_article_content(article_id)
            if content_sentences is None:
                print(f"Skipping article {article_id}: Content not found.")
                continue
            
            # For prompt generation, join content and comments into strings
            content_str_for_prompt = ' '.join(content_sentences)
            original_comments_str_for_prompt = ' '.join(original_comments)

            include_tokens = self.load_bert_tokens(article_id, is_fake_target=(target_class == 'FAKE'), top_n=top_n)
            avoid_tokens = self.load_bert_tokens(article_id, is_fake_target=(target_class == 'REAL'), top_n=top_n)

            if not include_tokens:
                 print(f"Skipping article {article_id}: No BERT 'include' tokens found.")
                 # Log failure for this article_id across all models if desired
                 for llm_model_name_skip in llm_models:
                    err_result = {
                        'id': article_id, 'model': llm_model_name_skip, 'status': 'No Include Tokens',
                        'dataset': self.dataset_name.capitalize(), 'attack_type': attack_type,
                        'original_predicted': predicted_label, 'target_class': target_class,
                        'scenario_1': {'success': False, 'original_prediction': {}, 'modified_prediction': {}},
                        'scenario_2': {'success': False, 'original_prediction': {}, 'modified_prediction': {}}
                    }
                    comparison_results[llm_model_name_skip].append(err_result)
                 continue

            for llm_model_name in llm_models:
                print(f"\n-- Article {article_id}, LLM: {llm_model_name}, Loading/Generating Comment --")

                comment_folder_name = f"model_comparison_{generated_comments_folder_suffix}"
                comment_json_path = os.path.join(
                    PRE_GENERATED_COMMENTS_BASE_DIR, self.dataset_name, "bert-attack-result",
                    comment_folder_name, f"attack_{article_id}_{llm_model_name}.json"
                )
                processed_comment = None
                try:
                    with open(comment_json_path, 'r') as f_json:
                        comment_data = json.load(f_json)
                        processed_comment = comment_data.get("generated_comment")
                    if processed_comment:
                        print(f"Loaded pre-generated comment for article {article_id}, model {llm_model_name}: {processed_comment[:100]}...")
                    else: # Fallback to generation if key missing or comment empty
                        print(f"Warning: 'generated_comment' key not found or empty in {comment_json_path}. Triggering generation.")
                        raise FileNotFoundError 
                except (FileNotFoundError, json.JSONDecodeError) as e_load:
                    if isinstance(e_load, FileNotFoundError):
                        print(f"Pre-generated comment file not found or empty for {article_id}, LLM {llm_model_name}. Attempting generation: {comment_json_path}")
                    else: # JSONDecodeError
                        print(f"Error decoding JSON for {article_id}, LLM {llm_model_name}. Attempting generation: {comment_json_path}")
                    
                    os.makedirs(os.path.dirname(comment_json_path), exist_ok=True)
                    
                    # Use joined strings for prompt creation
                    prompt = self.create_comment_generation_prompt(
                        title_str, content_str_for_prompt, original_comments_str_for_prompt, 
                        include_tokens, avoid_tokens, target_class, generated_comments_folder_suffix
                    )
                    generated_comment_raw = self.query_ollama(prompt, attack_type, model_name=llm_model_name)
                    processed_comment = self.process_generated_comment(generated_comment_raw)

                    if processed_comment:
                        print(f"Successfully generated a new comment for {article_id}, model {llm_model_name}.")
                        temp_used_tokens, temp_num_used_tokens = self.verify_token_usage(processed_comment, include_tokens)
                        temp_non_used_tokens, temp_num_non_used_tokens = self.verify_token_usage(processed_comment, avoid_tokens)

                        # Use lists for test_attack_success
                        # Scenario 1: Content + Generated Comment (vs Content only)
                        temp_scenario_1_result = self.test_attack_success(
                            content_sentences, # list of sentences
                            [],                # original comments for this scenario (empty list)
                            [processed_comment],# list containing the generated comment
                            is_fake_pred       # boolean: True if dEFEND originally predicted FAKE
                        )

                        # Scenario 2: Content + Original Comments + Generated Comment (vs Content + Original Comments)
                        temp_scenario_2_result = self.test_attack_success(
                            content_sentences, # list of sentences
                            original_comments, # list of original comment strings
                            [processed_comment],# list containing the generated comment
                            is_fake_pred       # boolean: True if dEFEND originally predicted FAKE
                        )

                        comment_to_save_data = {
                            'id': article_id, 'model': llm_model_name, 'dataset': self.dataset_name.capitalize(),
                            'attack_type': attack_type, 'original_predicted': predicted_label,
                            'target_class': target_class, 'generated_comment': processed_comment,
                            'used_tokens': temp_used_tokens, 'num_used_tokens': temp_num_used_tokens,
                            'avoid_tokens': temp_non_used_tokens, 'num_avoid_tokens': temp_num_non_used_tokens,
                            'scenario_1': temp_scenario_1_result, # Store the whole result dict
                            'scenario_2': temp_scenario_2_result  # Store the whole result dict
                        }
                        try:
                            with open(comment_json_path, 'w') as f_out:
                                json.dump(comment_to_save_data, f_out, indent=2)
                            print(f"Saved newly generated comment and results to: {comment_json_path}")
                        except Exception as e_save:
                            print(f"Error saving newly generated comment to {comment_json_path}: {e_save}")
                    else:
                        print(f"Failed to generate a new comment for {article_id}, model {llm_model_name} after attempting.")
                except Exception as e: # Catch any other exception during loading/generation
                    print(f"An unexpected error occurred for article {article_id}, LLM {llm_model_name} before attack tests: {e}")


                if not processed_comment:
                    print(f"Skipping article {article_id} for model {llm_model_name} due to missing/failed comment generation.")
                    # Record failure if comment couldn't be loaded or generated
                    result = {
                        'id': article_id, 'model': llm_model_name, 'status': 'Comment Load/Gen Failed',
                        'dataset': self.dataset_name.capitalize(), 'attack_type': attack_type,
                        'original_predicted': predicted_label, 'target_class': target_class,
                        'scenario_1': {'success': False, 'original_prediction': {}, 'modified_prediction': {}},
                        'scenario_2': {'success': False, 'original_prediction': {}, 'modified_prediction': {}}
                    }
                    comparison_results[llm_model_name].append(result)
                    # Save individual failure JSON
                    with open(os.path.join(comparison_dir, f"attack_FAILED_{article_id}_{llm_model_name}.json"), 'w') as f:
                        json.dump(result, f, indent=2)
                    continue

                used_tokens, num_used_tokens = self.verify_token_usage(processed_comment, include_tokens)
                non_used_tokens, num_non_used_tokens = self.verify_token_usage(processed_comment, avoid_tokens)

                # Use lists for test_attack_success
                # Scenario 1: Content + Generated Comment (vs Content only)
                scenario_1_result = self.test_attack_success(
                    content_sentences, # list of sentences
                    [],                # original comments for this scenario (empty list)
                    [processed_comment],# list containing the generated comment
                    is_fake_pred       # boolean: True if dEFEND originally predicted FAKE
                )

                # Scenario 2: Content + Original Comments + Generated Comment (vs Content + Original Comments)
                scenario_2_result = self.test_attack_success(
                    content_sentences, # list of sentences
                    original_comments, # list of original comment strings
                    [processed_comment],# list containing the generated comment
                    is_fake_pred       # boolean: True if dEFEND originally predicted FAKE
                )
                
                result = {
                    'id': article_id, 'model': llm_model_name, 'dataset': self.dataset_name.capitalize(),
                    'attack_type': attack_type, 'original_predicted': predicted_label,
                    'target_class': target_class, 'generated_comment': processed_comment,
                    'used_tokens': used_tokens, 'num_used_tokens': num_used_tokens,
                    'avoid_tokens': non_used_tokens, 'num_avoid_tokens': num_non_used_tokens,
                    'scenario_1': scenario_1_result, # Store the whole result dict
                    'scenario_2': scenario_2_result  # Store the whole result dict
                }
                comparison_results[llm_model_name].append(result)
                with open(os.path.join(comparison_dir, f"attack_{article_id}_{llm_model_name}.json"), 'w') as f:
                    json.dump(result, f, indent=2)
        
        # --- Save Aggregate Summary ---
        summary_rows = []
        for model, results in comparison_results.items():
            for scenario in ['scenario_1', 'scenario_2']:
                for attack_type in ['Fake', 'Real']:
                    filtered = [r for r in results if r['attack_type'] == attack_type]
                    if not filtered:
                        continue
                    success_count = sum(1 for r in filtered if r[scenario]['success'])
                    total = len(filtered)
                    success_rate = 100 * success_count / total if total else 0
                    summary_rows.append({
                        'Model': model,
                        'Dataset': filtered[0]['dataset'] if filtered else self.dataset_name.capitalize(),
                        'Attack_Scenario': 'Scenario 1 (zero comments)' if scenario == 'scenario_1' else 'Scenario 2 (ten comments)',
                        'Attack_Type': attack_type,
                        'Attack_Success_Rate': f"{success_rate:.2f}%"
                    })

        # Save and print summary
        summary_df = pd.DataFrame(summary_rows)
        summary_csv_path = os.path.join(comparison_dir, "attack_summary.csv")
        summary_df.to_csv(summary_csv_path, index=False)

        print("\nAttack Summary Table:")
        print(summary_df.to_string(index=False))

        return comparison_results

# --- Main Execution Block ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="dEFEND Adversarial Attack using BERT SHAP tokens and LLM Comparison")
    parser.add_argument("--dataset", type=str, default="gossipcop", choices=["gossipcop", "politifact"], help="Dataset to use")
    parser.add_argument("--max-examples", type=int, default=0, help="Max correctly predicted examples by dEFEND to attack (0 for all)")
    parser.add_argument("--top-n", type=int, default=200, help="Number of top BERT SHAP tokens to use")
    parser.add_argument("--model", type=str, default="llama3:8b", help="Base Ollama model for comments")
    parser.add_argument("--compare", action="store_true", help="Compare with additional models")
    parser.add_argument("--compare-with", type=str, default="", help="Additional Ollama models (comma-separated)")
    parser.add_argument(
        "--prompt-style", type=str, required=True,
        choices=["title", "title_article", "title_cmnts", "title_article_cmnts"],
        help="Suffix for pre-generated comments folder (e.g., 'title_cmnts')"
    )
    args = parser.parse_args()

    max_examples_limit = None if args.max_examples <= 0 else args.max_examples

    attacker = DefendAttackerWithBertTokens(args.dataset)

    predictions_csv_path = os.path.join(attacker.results_dir, "predictions.csv")
    try:
        all_predictions_df = pd.read_csv(predictions_csv_path)
        if 'correct' not in all_predictions_df.columns or 'predicted' not in all_predictions_df.columns:
            raise ValueError("dEFEND predictions CSV must contain 'correct' and 'predicted' columns.")
        
        # Filter for examples dEFEND predicted correctly
        correct_predictions_df = all_predictions_df[all_predictions_df['correct'] == 1].copy()
        if correct_predictions_df.empty:
            print(f"No correctly predicted examples by dEFEND found in {predictions_csv_path}. Exiting.")
            exit()
        print(f"Loaded {len(all_predictions_df)} total predictions, {len(correct_predictions_df)} correctly predicted by dEFEND.")
    except FileNotFoundError:
        print(f"Error: dEFEND predictions file not found at {predictions_csv_path}. Generate it first. Exiting.")
        exit()
    except Exception as e:
        print(f"Error reading dEFEND predictions file {predictions_csv_path}: {e}. Exiting.")
        exit()

    if max_examples_limit:
        correct_predictions_df = correct_predictions_df.head(max_examples_limit)
        print(f"Limiting attack to the first {len(correct_predictions_df)} correctly predicted examples.")

    llm_models_to_compare = [args.model.strip()]
    if args.compare and args.compare_with:
        additional_llms = [m.strip() for m in args.compare_with.split(',') if m.strip()]
        llm_models_to_compare.extend(additional_llms)
        seen_llms = set()
        llm_models_to_compare = [m for m in llm_models_to_compare if not (m in seen_llms or seen_llms.add(m))]
    
    print(f"\n--- Starting dEFEND Attack using BERT Tokens ---")
    print(f"Dataset: {args.dataset}")
    print(f"Max Examples: {'All Correct' if max_examples_limit is None else max_examples_limit}")
    print(f"Top N BERT Tokens: {args.top_n}")
    print(f"LLM Models for Attack: {', '.join(llm_models_to_compare)}")
    print(f"dEFEND Model Path: {os.path.join(attacker.defend_model_path_dir, attacker.defend_model_filename)}")
    print(f"BERT Token Path: {attacker.bert_token_dir}")
    print(f"dEFEND Predictions Path: {predictions_csv_path}")
    print(f"Output Directory Base: {attacker.attack_dir}")
    print(f"Prompt Style for Pre-gen Comments: {args.prompt_style}")
    print(f"-------------------------------------------------")

    attacker.compare_models(
        predictions_df=correct_predictions_df,
        generated_comments_folder_suffix=args.prompt_style,
        llm_models=llm_models_to_compare,
        top_n=args.top_n
    )

    print("\n--- dEFEND Attack Run Finished ---")